project:
  type: website
  pre-render: scripts/pre_render.py

metadata-files:
  - _generated/_sidebars.yml



website:
  title: "Zawaの勉強記録"
  repo-url: "https://github.com/IR25721/Zawa25721_documents#"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.md
        text: はじめに
    right:
      - icon: github
        href: "https://github.com/IR25721/Zawa25721_documents#"

format:
  html:
    html-math-method: katex
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false
    grid:
      body-width: 1400px
      margin-width: 300px
      gutter-width: 2rem
