project:
  type: website
  pre-render: pre_render.py

metadata-files:
  - _sidebars.yml



website:
  title: "My Portal"
  repo-url: "https://github.com/IR25721/Zawa25721_documents#"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.md
        text: はじめに
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: "https://github.com/IR25721/Zawa25721_documents#"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false
